name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        # Add any build commands you need here
        # For example, if you're using a static site generator like Jekyll:
        # bundle install
        # bundle exec jekyll build

        # Deploy to GitHub Pages
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add gh-pages https://github.com/${{ github.repository }}.git
        git checkout -b gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force gh-pages

    - name: Cleanup
      run: |
        git checkout ${{ github.ref }}
        git branch -D gh-pages
      if: success()
